### ISSUE TITLE
Formatting of note boxes

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#335] opened 2021-10-09 22:33 UTC
The end of the note line appears two pages later with figures in between
<img width="801" alt="Screen Shot 2021-10-09 at 3 32 44 PM" src="https://user-images.githubusercontent.com/3838091/136675284-861ee514-3d57-46d0-9450-0cc3368cca2e.png">
<img width="713" alt="Screen Shot 2021-10-09 at 3 32 23 PM" src="https://user-images.githubusercontent.com/3838091/136675279-7b94c8d9-d9da-4a0a-b9e0-09bec2cd08ec.png">

**Comment by leem44** [comment] 2021-10-09 22:35
Same kind of thing here: 
<img width="736" alt="Screen Shot 2021-10-09 at 3 34 53 PM" src="https://user-images.githubusercontent.com/3838091/136675319-7405377a-b4f9-4c2f-ba2a-21b98b007798.png">

**Comment by trevorcampbell** [comment] 2021-10-21 01:13
Duplicate of #356

**Closed by trevorcampbell** 2021-10-21 01:13 UTC
Labels: bug
