### ISSUE TITLE
output from tidymodels goes past margins

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#321] opened 2021-10-08 20:56 UTC
This is from classification 1 
<img width="811" alt="Screen Shot 2021-10-08 at 1 55 40 PM" src="https://user-images.githubusercontent.com/3838091/136623858-73ce78b1-e900-4881-bbe0-9070f68be7e9.png">

**Comment by trevorcampbell** [comment] 2021-10-09 07:02
duplicate of #329 , closing

**Closed by trevorcampbell** 2021-10-09 07:02 UTC
Labels: bug
