### ISSUE TITLE
For loop in classification chapter

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#242] opened 2021-09-22 23:26 UTC
This code block has a for loop in it. Tiffany said she would make a package for fwd selection, and we should definitely make sure to do that. Might want to ping her to do that and then edit this PR accordingly.

_Originally posted by @trevorcampbell in https://github.com/UBC-DSCI/introduction-to-datascience/pull/234#discussion_r713598251_

**Comment by trevorcampbell** [comment] 2023-08-05 22:38
Duplicate of #148

**Closed by trevorcampbell** 2023-08-05 22:38 UTC
Labels: v2 enhancement
