### ISSUE TITLE
Review: Global/big picture content revisions

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#95] opened 2021-03-22 18:57 UTC
@trevorcampbell @leem44 - let's list the global/big picture content revisions asked for in review here. When adding please do not duplicate things, just edit the list noting that it was asked for by X number of reviewers.

**Comment by leem44** [comment] 2021-03-28 17:40
From reviewer E:

### reservations
- textbook feels more like course notes than a stand-alone text e.g.:
    -  references to the video content could be cleaned up
    - additional resources could be annotated to explain what students should hope to learn from reading them
    - more frameworks could be described for things such as the modeling process
    - it’s less clear what is meant to illustrate an example versus the universe of possibilities -- worth being more specific about things that are just high-level examples (e.g. KNN versus all classification algorithms). 

- book does not take a very opinionated stance on some of the real-world skills needed to succeed in data science (e.g. Ch 4 took a strong and opinionated stance on the right way to effectively explain a visualization). would find the whole book significantly more valuable if this voice were present throughout.
- some aspects of `dplyr` and `ggplot2` that should be updated to the “latest and greatest” approach (following the recent release of dplyr 1.0.0) over older alternatives
- tying together intro to `tidyverse` (like R for Data Science) and a classic introduction to modelling (like ISLR) and showing the complete workflow. book can be crisper on each step of the process and provide a view on the algorithmic, technical, and creative sides of data science. 

### additions:
- add glossary of main functions discussed to the appendix. 
- Before beginning modeling, describe the model building process (data wrangling, picking an algorithm, tuning it with training data, evaluating it on test data, etc.) While all of the components are described, it may be hard for new readers to clearly separate out data, algorithms, parameters, and evaluation metrics without a framework. This could include some of the content about evaluation in Chapter 7 but not specific to classification.
- discuss feature engineering. common misconception with early-stage data scientists that they can simply model off of whatever fields happen to appear in their table. Critically thinking about what features to include in a model is particularly important with algorithms like KNN (a focus of the book) for which performance can be significantly degraded with irrelevant predictors. Additionally, this is a way to link the skills learned in the first and second halves of the book. 
- While the book may not explain many different algorithms, could do more to acknowledge their existence. readers might come away thinking that classification is KNN, regression is linear modeling, clustering is K-means, and inference is comparison of means. It might be good to list other common algorithms in each chapter and even briefly mention when alternatives might be preferred. 

### omissions:
- consider removing references to JupyterHub or moving them to an appendix. All of the book content is highly relevant apart from any specific analytical platform, so this could increase the book’s appeal to a wider audience.
- Chapter 5 felt somewhat misplaced in terms of placement and content.
  - breaks the narrative flow of focusing of data analysis and analytical tools -- might work better in an introduction and set-up set of chapters (perhaps combined with Chapter 12) or in an appendix. 
  - However, content may not be useful in a book format. Jupyter Notebooks may be a particularly hard type of file to use to teach this skill since they aren’t plaintext and don’t produce clean diffs. 
  - discussion of GitHub relies on screenshots that risk going stale and doesn’t describe the most common GitHub usage patterns (via command line). Such platforms maintain good documentation, and theirs is less likely to go stale as they change their interface. If you do wish to give instructions, consider describing how to use the command line or GitHub Desktop, as the method shown (uploading manually via the UI) is not sustainable or very representative of common usage. 
  
### examples
- fatiguing that every single example uses a different and completely unrelated dataset. 
  - Reader spends more time thinking about the data itself than about the methods being taught, and the lack of emphasis on explaining data makes the dangerous subtle implication that data science can be done without a deep understanding of data and domain. 
  - rather see a small set of datasets to use consistently throughout the book and explicitly introduce these at the beginning
  -or perhaps convert the whole book to continually point back to a single more realistic case study. 
- Some examples do a great job of “spiraling” and iteratively mixing new and previously learned concepts step-by-step. (e.g. in the ggplot2 section). would love to see it applied more consistently. many parts of the book function in silos; for example, none of the modeling sections rely much on the previous teaching of `dplyr` for EDA
- all examples are “toy” examples and dodge a good bit of the real-world complexity of data analysis. This is likely by design because it helps students focus on key concepts, but it might be worth acknowledging some of the simplifications (e.g. data cleaning, feature engineering, checking for missing data, constraining assumptions of different algorithms) so students are not blindsided when they encounter these in practice. 
- could supplement practice problems with assignments from their corresponding course, which could potentially make this book a much more useful resource for self-study. 

### length
- book is on the shorter side, but that may be appealing to students and make it seem very manageable for use in either a course or self-study. If the book does grow in length, could mitigate any downside by laying out different “learning paths” or highlighting required versus optional chapters in the introduction.

**Comment by leem44** [comment] 2021-03-28 18:38
Reviewer B: 
- would love to hear the reasoning behind choosing JupyterHub. Perhaps in a blogpost when the book comes out? I’m sure a lot of other R-centric instructors would like to know. 
- I like the idea of exposing students to a workspace that’s Julia and python friendly too. ...this would be like working a makerspace where Julia and python tools were also being used by others. That way R tool users will see/recognize when other tools are being used.

**Comment by trevorcampbell** [comment] 2021-03-28 20:06
# Reviewer D

- The titles of the chapters in the second part of the manuscript (from Classification and beyond) seem overly technical.  Is there a way to couch them so that students/readers understand from a first glance what is really going on in those chapters?  For example, the chapter titled “Moving to your machine” (too technical!) could be called something like “Running R commands on your own computer”.

**Comment by trevorcampbell** [comment] 2021-03-28 20:42
# Reviewer A
- My biggest reservation about the manuscript is the absence of end-of-chapter exercises. I don’t think a novice reader will be able to really grasp the material deeply without some (guided) practice, and end of chapter exercises are a great way to do that. It’s also important to note that competitors to this book do have exercises.
    - tutorials + worksheets
- no major revisions are needed for existing chapters.
- I do think a “Where to go from here?” chapter would help the reader. This is a truly introductory text, so if a there is a reader that isn’t using it for a course, it would be great to provide some guidance about their path forward.
- chapter titles are appropriate. I do think using a “multivariate regression” title might be confusing (I’ve marked it on the PDF), since when I hear multivariate regression, I think about modeling multiple response variables simultaneously. Instead, perhaps multiple regression or regression with multiple predictors would be clearer.
- expand the brief introduction of what data science is and what the book will cover. Maybe mentioning case studies or giving more detailed examples would help. This would give the reader a more anchored intro to the discipline rather than just the book and might pique more interest.

**Comment by trevorcampbell** [comment] 2021-03-28 21:49
### Edit this comment directly to summarize / synthesize the major (important) comments across reviewers. If there's already the same comment below, add the reviewer to the parenthetical list at the beginning.

# Synthesis:
- We need to include exercises (that's easy -- just include tut + wksht)
- Add a "where to go from here" chapter?
- Expand the brief introduction paragraph in Chapter 1 to be more clear about what the book covers. Rev D suggests a whole chapter for this. Rev A suggests just expanding the paragraph.
- we could put tables throughout the text to highlight the overall set of "options" for a given task (see the detailed comment on Ch4 Viz for an example of what RevD means)
- The book makes a lot of reference to doing things on JHub / JLab. How should the reader follow these things? Some reviewers like the focus on JHub/Lab, some really don't. Some want more reasoning behind it.
- There are a lot of links to external material (videos, worksheets, etc) that won't make sense for the general reader (not dsci100 students), and won't translate to print format. This will be helped a bit if we include tuts and wkshts along with the book. But the print format videos and 3d plots etc still need fixing.
- Reviewer D comment re: inductive vs deductive approach
- Move the collaboration section to the end of the book
- make a better title (it's too dry)
- rename "chapter learning objectives" to "skill building objectives"?

**Comment by ttimbers** [comment] 2021-03-29 19:45
# Reviewer F

- Overreliance on Jupyter notebooks (e.g. RStudio cloud used to be free and then restrictions were introduced to push sales to educational institutions) – there should be an option for RStudio desktop as an alternative. Eventually, you want students to use RStudio as they progress in their career, JP may not be a permanent option.
- Some explanations even though they are marked as option create a confusion – for example on p7 reference to the base functions… just say – there are many ways to do the same thing!
- Introduction seems most problematic… lots of things covered at a high speed and they are repeated (reiterated?) in later chapters… e.g. grammar of graphics – at least some understanding of basic PRINCIPLES, rather then these are the steps to follow would be good.
- Some basic introduction of data types is needed, e.g. introduction refers to data frame but “what is this?????” – why should your readers know???
- - Chapters are quite “technical” and does assume some knowledge as well as “homework” preparation using other resources, suggested by the authors though.
- Chapters are filled with examples – which is fantastic, but some key knowledge is missing. E.g. visualization chapter just sends the reader to other textbook to read how to build visualizations and goes into details of what “effective visualizations are”. You can lose your reader in that “other” textbook and they never come back for the examples here.
- Machine learning principles need a chapter on its own (e.g. training/testing datasets, metrics and evaluation of models, bias/variance, etc.). Explaining the logic behind tidymodels also would be great – at this stage authors just “jump” into it. 
Introduction to statistical inference feels out of place, after Cluster analysis chapter it feels a bit too late….
- Appropriate, but datasets may need a bit more introduction. For the future – it may be good to stick with less datasets – to demonstrate how the same data can answer different questions.
- The book feels more like a reference manual or.. workshops materials… It is assumed that “theory” and foundations are covered somewhere else. Some fundamental knowledge and principles are missing – for example, Regression I: K-nearest neighbours section misses the explanation of the method and it is the first part of the regression method.. It just starts with a working example assuming that the readers “get” what the authors are referring to.
- The book is quite technical and does assume some experience. Could be a good reference book to “structure” and “organize” existing knowledge. Has too much “read this if you want more details” or “understand this”.  The content is “to the point” but can be hard to “digest” for newbies.
- Is the author’s approach to the subject appropriate for the intended level of the target audience? 
Well, for outstanding students in the cohort – it is a brilliant manuscript, but for the rest of the crowd (which may be the majority)…
- Good book, one of the best manuscripts in terms of concise coverage, organized flow and structure and care about Teaching&Learning process. However, the book has a common issue for textbooks – cover everything in the concise form.

**Comment by ttimbers** [comment] 2021-03-29 19:52
# Reviewer C
- Pace: I think the material is too fast and too dense for someone to work through on their own. I think that in
a lab setting, with a tutor there to answer questions and elaborate on the provided examples, it would be
fine, but as a stand-alone learning resource, it would be a real challenge for most of the learners I’ve had.
(This is particularly true of the chapter on Git, which is famously difficult to teach.)
- Consolidation: there are many places where it feels like the chapters were written independently and then
stitched together – some things are covered twice, some things are used before they are defined, etc.
Sometimes this is OK (I don’t think the authors need to explain what the ‘min()’ function does before using
it), but in general, I think that going through the first five chapters and making a point-form list of every
new concept or function introduced, then checking the ordering, would help a lot.
- There are also places where it feels like the book is written for other instructors rather than for students – I
have noted these in the PDF.
- I believe most readers will want more examples – many important topics are shown (or explained) at most once.
- I would like many more diagrams (as opposed to plots or screenshots). This would be particularly helpful when
explaining the layers in ggplot2 graphics, and in explaining the lifecycle of Git commits, pushes, pulls, and merges.
- I think more examples are needed to illustrate key points.
- The bullet lists for things like image file formats and other version control systems feel like instructors’
notes rather than teaching material.
- I would move the point-form learning objectives to an appendix: they really are intended for other
instructors rather than for learners.
- More diagrams please.
- I think the book has tremendous potential, but as I’ve said above, many readers (particularly those without a strong
programming background) will find it extremely dense. More examples, more diagrams, less jargon, and fewer
forward references or unexplained concepts and terms will help a lot.

**Comment by ttimbers** [comment] 2021-04-07 19:54
## Action items

Revision of synthesis into action items. We might want to pull these off into individual issues we can close as we address them, and assign folks to them.

1. **Stable domain and links**. Get a domain, that we can use to come up with stable links for linking to videos and worksheets from the textbook.

2. **Exercises/worksheets**. Create repository for just worksheets to be associated with the textbook.  (Bonus 1: Perhaps we can use Binder or a Public JupyterHub to make them interactive? Bonus 2: Add GitHub Actions to the repo to use Jupytext to autogenerate Rmd's of the worksheets for folks who'd prefer to work with Rmd instead of Jupyter?) Point to the relevant worksheet at the end of each chapter using a stable link. Remember, when we point to the worksheets, to also point to the system setup chapter so they can first follow the instructions of setting up Jupyter on their own machine. (+1 Reviewer E and B)

3. **Improve additional resources sections**. Add a few sentences to give context to each additional resource we share. This means going just beyond annotating them (we should also do that), but also explain what topic they should focus on next. *Rebut: We will not add a where to go from here chapter, asked by reviewer ?, but will instead do better job at the end of each chapter, on a topic-by-topic basis.*

4. **Revise chapter 1 (introduction)**: Expand the brief introduction paragraph in chapter 1 to be more clear about what the book covers. Specifically:
    - tell people how to read the book (might want to read the system setup ~~and version control chapters first~~)
    - add data science workflow diagram to beginning of chapter 1, & expand text to make it clearer what is going on
    - move `select` & `filter` to wrangling (chapter 3) and make sure this doesn't negatively affect chapter 2
    - move Jupyter content to System setup/Setting up your computer chapter
    
    This addresses comments by Rev D, Rev A & C. Need to rebut D's ask for a whole new chapter here.

5. **Move Jupyter-related content to System-setup chapter**: Rename "Moving to your own machine" to "System setup" (or something related? Like "Setting up your computer?"?) and move any Jupyter-related content there. We can then link to it from other chapters if needed. Bonus: can we also explain how to get setup and use Rmd with RStudio so our book can support both major DS literate code document platforms? Or at a minimum link out to other good resources on this (risk: they don't come back to us...). UI (how to use Jupyter & Rmd) stuff becomes videos with stable links. This addresses comments made by Rev C, E.

6. **Move version control chapter to the end of the book and revise chapter to be more conceptual**. Add more conceptual content to the vc chapter, and diagrams (like [these](https://github.ubc.ca/UBC-DSCI/dsci-100-instructor/tree/master/slides/img/git_intro)), and move the screenshots to a screen cast with a stable link. Might want to consider doing both a Jupyter Git Extension demo, and an RStudio one. This addresses comments made by Rev C & F.
  
7. **Update to the newest `dplyr` and `ggplot2`**. Check most recent updates to `dplyr` and `ggplot2` and make sure we are using the most up to date syntax in the books. If this needs to change, also change in the worksheets. This addresses comments made by Rev A & E.

8. **Fix/improve index**. We need a robust index for this book. Check whether this can be autogenerated by `bookdown`? Talk to Laura (CRC Press) for help on this if we need to? Also, once we create the index, we want to create a glossary of the main terms and functions. Let's consider using the [`glossario` R package](https://github.com/carpentries/glosario) for this, and borrowing from the [Carpentries English glossary](https://glosario.carpentries.org/en/)? This addresses comments made by Rev E.

9. **Ensure we just teach one way to do things**. Read through the book and check that we only teach one way to do things (although we can acknowledge there are many ways to do things): Specifically, find where we have shown alternatives and make sure we are clear the way we want them to do it with `tidyverse`. This addresses comments made by Rev C.

10. **Simplify and better explain data sets**. Where we can, provide more information/context about the data sets (maybe in a call out box or something?). Also, make it clear where things have been simplified and why (so we can focus on the data science method we are teaching). At a minimum, we need to explicitly state that data science **cannot** be done without a deep understanding of data and domain, and that we are approaching things the way we are to teach data science, and IRL data science should not be done without a domain expert, or alternatively, it is common to practice data science in your domain of expertise.*  Go through each chapter and find where we can just have one data set. Idea: see if we can have chapter 2 only use `canlang` data sets (might not work for web scraping, but maybe there's a more related data set? Note: Chapter 4 needs multiple data sets by the way we have written it. Question: Think about clustering chapter - can we use one that we are already using? This addresses comments made by Rev C & E, but we do need to also generate a rebuttal here stating why we have chosen a rich set of data sets for this book.

11. **Revise supervised learning chapters**. 
    - Add high-level sections to 6 (process - train & evaluate, 6 will cover train, 7 covers evaluate) & 8 (acknowledge that this is a repeat of 6 & 7 with a new flavour)
    - add a wrap-up/summary at the end of 9 that brings everything together in context (we could introduce the term supervised learning, and hint that the next chapter covers a new type of analysis for a different problem, that is called unsupervised learning)
    - 
    
    This will address comments made by Rev C & E.

12. **Improve regression introduction**. Lead into regression more gentle and rely less on past knowledge about classification (8.3 is a bit bizarre, should combine with 8.4). This will address comments made by Rev C.

13. **Add vector data types explanations**. Add base R vector types (logical, integer, double, character) introduction and explanation to section 3.3.2 ("What is a vector?") in chapter 3. Add factor vector type explanation in chapter 4 (visualization chapter), when we need it. This will address comments made by Rev C & E.

14. **Ensure book is written for intended audience**. Read through reviewer C's annotations and address highlighted parts where book appears to be written for other instructors rather than for students. This will address comments made by Rev C.

-- ONLY MADE IT TO HERE SO FAR --


- (Reviewer E): textbook feels more like course notes than a stand-alone text e.g.: 
  - [ ] references to the video content could be cleaned up
  - more frameworks could be described for things such as the modeling process *????????*
  - [ ] it’s less clear what is meant to illustrate an example versus the universe of possibilities -- worth being more specific about things that are just high-level examples (e.g. KNN versus all classification algorithms). *For example, make it clear what parts of chapter 7 are relevant to classification in general, and which are relevant to just k-nn*

- [ ] (Reviewer E) book does not take a very opinionated stance on some of the real-world skills needed to succeed in data science (e.g. Ch 4 took a strong and opinionated stance on the right way to effectively explain a visualization). would find the whole book significantly more valuable if this voice were present throughout. (Reviewer E) - tying together intro to `tidyverse` (like R for Data Science) and a classic introduction to modelling (like ISLR) and showing the complete workflow. book can be crisper on each step of the process and provide a view on the algorithmic, technical, and creative sides of data science. My favorite parts of the book came when the authors took a strong and opinionated stance (e.g. on the right way to effectively explain a visualization), and I would find the whole book significantly more valuable if this voice were present throughout.
  - *Rebuttal: TC: I disagree with this comment. Viz is inherently a more subjective topic, and I feel that the approach we took was strongly opinionated in an effort to argue that students should follow our approach. The other bits of the book are less subjective, as there is a definitive "right" and "wrong" way to do those things, and so less opinionated argumentation is necessary.*

- (Reviewer E) I think the book could benefit by discussing feature engineering. I see a common misconception with early-stage data scientists that they can simply model off of whatever fields happen to appear in their table. This leaves a lot of power on the table. Critically thinking about what features to include in a model is particularly important with algorithms like KNN (a focus of the book) for which performance can be significantly degraded with irrelevant predictors.. Additionally, this is a way to link the skills learned in the first and second halves of the book. 
 - [ ] add some guidance on feature engineering at the end of the regression chapter

- (Reviewer E) While the book may not explain many different algorithms, could do more to acknowledge their existence. readers might come away thinking that classification is KNN, regression is linear modeling, clustering is K-means, and inference is comparison of means. It might be good to list other common algorithms in each chapter and even briefly mention when alternatives might be preferred. *Will be addressed by one of the action items above*

- (Reviewer E) Chapter 5 felt somewhat misplaced in terms of placement and content.
  - breaks the narrative flow of focusing of data analysis and analytical tools -- might work better in an introduction and set-up set of chapters (perhaps combined with Chapter 12) or in an appendix.
  - However, content may not be useful in a book format. Jupyter Notebooks may be a particularly hard type of file to use to teach this skill since they aren’t plaintext and don’t produce clean diffs.
  - discussion of GitHub relies on screenshots that risk going stale and doesn’t describe the most common GitHub usage patterns (via command line). Such platforms maintain good documentation, and theirs is less likely to go stale as they change their interface. If you do wish to give instructions, consider describing how to use the command line or GitHub Desktop, as the method shown (uploading manually via the UI) is not sustainable or very representative of common usage. *Will be addressed by one of the action items above*

- (Reviewer E) Some of the examples do a great job of “spiraling” and iteratively mixing new and previously learned concepts step-by-step. This is especially true in the ggplot2 section. This is a fantastic approach, and I would love to see it applied more consistently. Unfortunately, many parts of the book function in silos; for example, none of the modeling sections rely much on previous teaching of dplyr for EDA which may leave students wondering why they even learned that content. *Rebuttal: we don't do this to focus on the modelling stuff, but this happens in the worksheets.*
- [ ] Create a putting it all together chapter (build off this: https://github.com/ttimbers/breast_cancer_predictor), minimum for classification, maximum for all - important to put it after the modelling chapters (leave some complexities in these examples, like cleaning data, etc)

- (Reviewer E) I also do notice that all examples are definitely “toy” examples and dodge a good bit of the real world complexity of data analysis. This is likely by design because it helps students focus on key concepts, but it might be worth acknowledging some of the simplifications (e.g. data cleaning, feature engineering, checking for missing data, constraining assumptions of different algorithms) so students are not blindsided when they encounter these in practice. *Will be addressed by one of the action items/rebuttals above*

- (Reviewer E) This book is definitely on the shorter side, but that may be particularly appealing to students and make it seem very manageable for use in either a course or self-study. That said, throughout this review, I do suggest some other potential types of content, and I do not think making the book longer to cover more ground would be a problem either.  If the book does grow in length, the author could mitigate any downside by laying out different “learning paths” or highlighting required versus optional chapters in the introduction. *Will be addressed by one of the action items/rebuttals above*

- [ ] Reviewer D comment re: inductive vs deductive approach - to do: add a summary of where we are going for each walkthrough example in the book (especially 6, 7, 8). 


- [ ] (Reviewer C) I think the book has tremendous potential, but as I’ve said above, many readers (particularly those without a strong programming background) will find it extremely dense. More examples, more diagrams, less jargon, and fewer forward references or unexplained concepts and terms will help a lot. *Go through book and look for forward references or unexplained concepts, also, we are adding more diagrams (etc version control chapter), rebut - worksheets allow them to revisit concepts in a more interactive and interesting way*.

- (Reviewer C) I recommend moving the material on web scraping much later in the book - learners are going to be struggling with the tidyverse at this point, and now you’re adding HTML and CSS etc. to their cognitive load. I agree it needs to be covered, but not here… -(+ Reviewer E) Given that understanding of students’ backgrounds, the only section that felt very out of place to be is the part on web scraping. As I elaborate in 11 (see here #102), the prevalence of Javascript pages makes this harder to do with rvest alone, and the increasing prevalence of APIs make this less necessary. This also requires a lot of extra knowledge (e.g. of HTML and CSS) that seem beyond the presumed background. *Rebut: this is extra/bonus material, we will make this more clear), also students love this content, so we don't want to remove it*
  - [ ] add subsection on web API's (we could use this one: https://cran.r-project.org/web/packages/cancensus/vignettes/cancensus.html)

## Rebuttals to write 
These things we are purely rebutting, not changing.
- ~~rename "chapter learning objectives" to "skill building objectives"? (Reviewer E) I would move the point-form learning objectives to an appendix: they really are intended for other instructors rather than for learners.~~ *We will rebut*
- (Reviewer C) Introduction to statistical inference feels out of place, after Cluster analysis chapter it feels a bit too late…. *Rebuttal: beginner level textbook, the idea is that this is the next thing we would study in detail. We made a pedagogical decision for this book and audience to have a very low bar for math/stat/etc)* 

## Still need to decide what to do for these:
- [ ] make a better title (it's too dry) - revisit title discussion we had earlier
- [ ? ] we could put tables throughout the text to highlight the overall set of "options" for a given task (see the detailed comment on Ch4 Viz for an example of what RevD means)

**Comment by trevorcampbell** [comment] 2021-10-04 21:36
@ttimbers @leem44 this is done now, right?

**Comment by trevorcampbell** [comment] 2022-01-12 07:34
Closing; we can re-open if needed.

**Closed by trevorcampbell** 2022-01-12 07:34 UTC
