### ISSUE TITLE
Formatting references printing year twice

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#243] opened 2021-09-23 17:25 UTC
There's something weird about how this is rendering. I see this on the rendered page:

"Stanford Health Care. 2021. “What Is Cancer?” 2021. https://stanfordhealthcare.org/medical-conditions/cancer/cancer.html."

2021 is printed twice...

_Originally posted by @trevorcampbell in https://github.com/UBC-DSCI/introduction-to-datascience/pull/234#discussion_r713487185_

**Comment by leem44** [comment] 2021-09-23 17:25
This occurs with a couple of the references so we should go through and check all of them

**Comment by trevorcampbell** [comment] 2021-09-23 21:45
@leem44 I'll bet it's because there are `@online` bibtex entries, which isn't standard. In the `makeindex` branch I had to convert these to `@misc`. Let me see whether the issue is fixed in that branch.

**Comment by trevorcampbell** [comment] 2021-09-24 04:02
I also noticed that the PDF bibliography output is really incomplete.

**Comment by trevorcampbell** [comment] 2021-10-07 00:48
This is no longer happening in either the PDF or HTML copy.

**Closed by trevorcampbell** 2021-10-07 00:48 UTC
Labels: bug
